name: finwise_app
description: "A Finance/Expense Manager app using AA's"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.4.6
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  mobx: ^2.2.1
  mobx_codegen: ^2.4.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.2.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: GtPro
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Bold.ttf
        - asset: assets/fonts/GTWalsheimPro-Medium.ttf
        - asset: assets/fonts/GTWalsheimPro-Regular.ttf

    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaRoundedLTStd-Bd.otf
        - asset: assets/fonts/HelveticaRoundedLTStd-BdCn.otf
        - asset: assets/fonts/HelveticaRoundedLTStd-Black.otf
